services:
  wml_frontend:
    build:
      context: .
      target: prod
    container_name: wml_frontend
    environment:
      NUXT_PUBLIC_API_BASE: ${NUXT_CSR_API_BASE}
      NUXT_SSR_API_BASE: ${NUXT_SSR_API_BASE}
    ports:
      - 3434:3000
    networks:
      wml-net:
    restart: unless-stopped

networks:
  wml-net:
    external: true
