services:
  wml_frontend:
    build:
      context: .
      target: prod
    container_name: wml_frontend
    environment:
      # PORT: 3000
      NUXT_PUBLIC_API_BASE: http://192.168.10.192:8484
      NUXT_SERVER_BASE: http://172.24.0.3:8000
    volumes:
      - ./logs:/app/backend/logs
    ports:
      - 3434:3000
    networks:
      wml-net:
    restart: unless-stopped

networks:
  wml-net:
    external: true
