"""DB creation

Revision ID: f61ccd545055
Revises: 
Create Date: 2024-09-27 22:08:20.855471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61ccd545055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(f"create schema backend")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('price', sa.Numeric(
                        precision=9, scale=2), nullable=True),
                    sa.Column('model', sa.String(length=255), nullable=True),
                    sa.Column('is_purchased', sa.Boolean(), nullable=False),
                    sa.Column('buy_date', sa.DateTime(), nullable=True),
                    sa.Column('guarantee', sa.Integer(), nullable=False),
                    sa.Column('guarantee_end_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('receipt', sa.String(), nullable=True),
                    sa.Column('shop', sa.String(length=255), nullable=True),
                    sa.Column('priority', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='backend'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products', schema='backend')
    # ### end Alembic commands ###
    op.execute("drop schema backend")
